# Generated by Django 2.0.7 on 2018-07-25 01:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulletin_detail', models.TextField(max_length=1000)),
                ('bulletin_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('bulletin_price', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=50, unique=True)),
                ('goods_price', models.CharField(max_length=50)),
                ('goods_flag', models.BooleanField()),
                ('goods_img', models.ImageField(upload_to='')),
                ('goods_detail', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_detail', models.TextField(max_length=1000)),
                ('message_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_account', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50, unique=True)),
                ('user_password', models.CharField(max_length=50)),
                ('user_ConInf', models.CharField(max_length=50, unique=True)),
                ('user_local', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='record_buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_buyer', to='webapp.User'),
        ),
        migrations.AddField(
            model_name='record',
            name='record_good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_good', to='webapp.Goods'),
        ),
        migrations.AddField(
            model_name='record',
            name='record_seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_seller', to='webapp.User'),
        ),
        migrations.AddField(
            model_name='message',
            name='message_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_from', to='webapp.User'),
        ),
        migrations.AddField(
            model_name='message',
            name='message_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_to', to='webapp.User'),
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_seller', to='webapp.User'),
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_type', to='webapp.Type'),
        ),
        migrations.AddField(
            model_name='friend',
            name='friend_userA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_userA', to='webapp.User'),
        ),
        migrations.AddField(
            model_name='friend',
            name='friend_userB',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_userB', to='webapp.User'),
        ),
        migrations.AddField(
            model_name='collect',
            name='collect_collector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collect_collector', to='webapp.User'),
        ),
        migrations.AddField(
            model_name='collect',
            name='collect_goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collect_goods', to='webapp.Goods'),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='bulletin_publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletion_publisher', to='webapp.User'),
        ),
    ]
