# Generated by Django 2.0.7 on 2018-07-25 02:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collect',
            name='collect_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
