# Generated by Django 2.0.7 on 2018-07-25 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_collect_collect_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_ConInf',
            new_name='user_contact',
        ),
    ]
