# Generated by Django 2.0.7 on 2018-07-25 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20180725_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_img',
            field=models.ImageField(upload_to='img'),
        ),
    ]
