# Generated by Django 2.0.7 on 2018-07-31 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_user_user_flag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='record_good',
            new_name='record_goods',
        ),
    ]
