# Generated by Django 2.0.7 on 2018-08-02 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20180731_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletin',
            name='bulletin_title',
            field=models.CharField(default=-1, max_length=100),
            preserve_default=False,
        ),
    ]
